/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserApprovalInfo {
    status: ApprovalStatus;
    principal: Principal;
}
export type Time = bigint;
export interface PayoutRecord {
    status: Variant_pending_completed_failed;
    amount: number;
    payoutDate: Time;
}
export interface PerformanceMetrics {
    clicks: bigint;
    lastUpdated: Time;
    commissionEarned: number;
    conversions: bigint;
}
export interface PartnerProfile {
    contactName: string;
    businessName: string;
    email: string;
    website: string;
    applicationDate: Time;
}
export enum ApprovalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_pending_completed_failed {
    pending = "pending",
    completed = "completed",
    failed = "failed"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    approvePartner(partner: Principal): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getAllPartnerApprovals(): Promise<Array<UserApprovalInfo>>;
    getAllPartners(): Promise<Array<PartnerProfile>>;
    getAllPayoutRecords(): Promise<Array<[Principal, Array<PayoutRecord>]>>;
    getAllPerformanceData(): Promise<Array<[Principal, PerformanceMetrics]>>;
    getCallerApprovalStatus(): Promise<ApprovalStatus>;
    getCallerPayoutRecords(): Promise<Array<PayoutRecord>>;
    getCallerPerformanceMetrics(): Promise<PerformanceMetrics | null>;
    getCallerProfile(): Promise<PartnerProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getPartnerApprovalStatus(partner: Principal): Promise<ApprovalStatus>;
    getPartnerDashboard(): Promise<{
        metrics: PerformanceMetrics;
        approvalStatus: ApprovalStatus;
        payouts: Array<PayoutRecord>;
        profile: PartnerProfile;
    }>;
    getPartnerProfile(partner: Principal): Promise<PartnerProfile>;
    getPayoutRecords(partner: Principal): Promise<Array<PayoutRecord>>;
    getPerformanceMetrics(partner: Principal): Promise<PerformanceMetrics>;
    isCallerAdmin(): Promise<boolean>;
    isCallerApproved(): Promise<boolean>;
    listApprovals(): Promise<Array<UserApprovalInfo>>;
    recordClick(partner: Principal): Promise<void>;
    recordConversion(partner: Principal, commission: number): Promise<void>;
    registerPartner(profile: PartnerProfile): Promise<void>;
    rejectPartner(partner: Principal): Promise<void>;
    requestApproval(): Promise<void>;
    requestPayout(amount: number): Promise<void>;
    setApproval(user: Principal, status: ApprovalStatus): Promise<void>;
    updatePayoutStatus(partner: Principal, payoutIndex: bigint, status: Variant_pending_completed_failed): Promise<void>;
}
import type { ApprovalStatus as _ApprovalStatus, PartnerProfile as _PartnerProfile, PayoutRecord as _PayoutRecord, PerformanceMetrics as _PerformanceMetrics, Time as _Time, UserApprovalInfo as _UserApprovalInfo, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async approvePartner(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approvePartner(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approvePartner(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAllPartnerApprovals(): Promise<Array<UserApprovalInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPartnerApprovals();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPartnerApprovals();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPartners(): Promise<Array<PartnerProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPartners();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPartners();
            return result;
        }
    }
    async getAllPayoutRecords(): Promise<Array<[Principal, Array<PayoutRecord>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPayoutRecords();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPayoutRecords();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPerformanceData(): Promise<Array<[Principal, PerformanceMetrics]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPerformanceData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPerformanceData();
            return result;
        }
    }
    async getCallerApprovalStatus(): Promise<ApprovalStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerApprovalStatus();
                return from_candid_ApprovalStatus_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerApprovalStatus();
            return from_candid_ApprovalStatus_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerPayoutRecords(): Promise<Array<PayoutRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerPayoutRecords();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerPayoutRecords();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerPerformanceMetrics(): Promise<PerformanceMetrics | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerPerformanceMetrics();
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerPerformanceMetrics();
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerProfile(): Promise<PartnerProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerProfile();
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerProfile();
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPartnerApprovalStatus(arg0: Principal): Promise<ApprovalStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getPartnerApprovalStatus(arg0);
                return from_candid_ApprovalStatus_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPartnerApprovalStatus(arg0);
            return from_candid_ApprovalStatus_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPartnerDashboard(): Promise<{
        metrics: PerformanceMetrics;
        approvalStatus: ApprovalStatus;
        payouts: Array<PayoutRecord>;
        profile: PartnerProfile;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getPartnerDashboard();
                return from_candid_record_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPartnerDashboard();
            return from_candid_record_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPartnerProfile(arg0: Principal): Promise<PartnerProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getPartnerProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPartnerProfile(arg0);
            return result;
        }
    }
    async getPayoutRecords(arg0: Principal): Promise<Array<PayoutRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPayoutRecords(arg0);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPayoutRecords(arg0);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPerformanceMetrics(arg0: Principal): Promise<PerformanceMetrics> {
        if (this.processError) {
            try {
                const result = await this.actor.getPerformanceMetrics(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPerformanceMetrics(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerApproved(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerApproved();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerApproved();
            return result;
        }
    }
    async listApprovals(): Promise<Array<UserApprovalInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApprovals();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApprovals();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async recordClick(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordClick(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordClick(arg0);
            return result;
        }
    }
    async recordConversion(arg0: Principal, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordConversion(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordConversion(arg0, arg1);
            return result;
        }
    }
    async registerPartner(arg0: PartnerProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerPartner(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerPartner(arg0);
            return result;
        }
    }
    async rejectPartner(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectPartner(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectPartner(arg0);
            return result;
        }
    }
    async requestApproval(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestApproval();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestApproval();
            return result;
        }
    }
    async requestPayout(arg0: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestPayout(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestPayout(arg0);
            return result;
        }
    }
    async setApproval(arg0: Principal, arg1: ApprovalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n19(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n19(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updatePayoutStatus(arg0: Principal, arg1: bigint, arg2: Variant_pending_completed_failed): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePayoutStatus(arg0, arg1, to_candid_variant_n21(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePayoutStatus(arg0, arg1, to_candid_variant_n21(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
}
function from_candid_ApprovalStatus_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStatus): ApprovalStatus {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_PayoutRecord_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PayoutRecord): PayoutRecord {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserApprovalInfo_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserApprovalInfo): UserApprovalInfo {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PerformanceMetrics]): PerformanceMetrics | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PartnerProfile]): PartnerProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: {
        pending: null;
    } | {
        completed: null;
    } | {
        failed: null;
    };
    amount: number;
    payoutDate: _Time;
}): {
    status: Variant_pending_completed_failed;
    amount: number;
    payoutDate: Time;
} {
    return {
        status: from_candid_variant_n13(_uploadFile, _downloadFile, value.status),
        amount: value.amount,
        payoutDate: value.payoutDate
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    metrics: _PerformanceMetrics;
    approvalStatus: _ApprovalStatus;
    payouts: Array<_PayoutRecord>;
    profile: _PartnerProfile;
}): {
    metrics: PerformanceMetrics;
    approvalStatus: ApprovalStatus;
    payouts: Array<PayoutRecord>;
    profile: PartnerProfile;
} {
    return {
        metrics: value.metrics,
        approvalStatus: from_candid_ApprovalStatus_n6(_uploadFile, _downloadFile, value.approvalStatus),
        payouts: from_candid_vec_n10(_uploadFile, _downloadFile, value.payouts),
        profile: value.profile
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ApprovalStatus;
    principal: Principal;
}): {
    status: ApprovalStatus;
    principal: Principal;
} {
    return {
        status: from_candid_ApprovalStatus_n6(_uploadFile, _downloadFile, value.status),
        principal: value.principal
    };
}
function from_candid_tuple_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, Array<_PayoutRecord>]): [Principal, Array<PayoutRecord>] {
    return [
        value[0],
        from_candid_vec_n10(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    failed: null;
}): Variant_pending_completed_failed {
    return "pending" in value ? Variant_pending_completed_failed.pending : "completed" in value ? Variant_pending_completed_failed.completed : "failed" in value ? Variant_pending_completed_failed.failed : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ApprovalStatus {
    return "pending" in value ? ApprovalStatus.pending : "approved" in value ? ApprovalStatus.approved : "rejected" in value ? ApprovalStatus.rejected : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PayoutRecord>): Array<PayoutRecord> {
    return value.map((x)=>from_candid_PayoutRecord_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserApprovalInfo>): Array<UserApprovalInfo> {
    return value.map((x)=>from_candid_UserApprovalInfo_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, Array<_PayoutRecord>]>): Array<[Principal, Array<PayoutRecord>]> {
    return value.map((x)=>from_candid_tuple_n9(_uploadFile, _downloadFile, x));
}
function to_candid_ApprovalStatus_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): _ApprovalStatus {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == ApprovalStatus.pending ? {
        pending: null
    } : value == ApprovalStatus.approved ? {
        approved: null
    } : value == ApprovalStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_pending_completed_failed): {
    pending: null;
} | {
    completed: null;
} | {
    failed: null;
} {
    return value == Variant_pending_completed_failed.pending ? {
        pending: null
    } : value == Variant_pending_completed_failed.completed ? {
        completed: null
    } : value == Variant_pending_completed_failed.failed ? {
        failed: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
