/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface PartnerProfile {
  'contactName' : string,
  'businessName' : string,
  'email' : string,
  'website' : string,
  'applicationDate' : Time,
}
export interface PayoutRecord {
  'status' : { 'pending' : null } |
    { 'completed' : null } |
    { 'failed' : null },
  'amount' : number,
  'payoutDate' : Time,
}
export interface PerformanceMetrics {
  'clicks' : bigint,
  'lastUpdated' : Time,
  'commissionEarned' : number,
  'conversions' : bigint,
}
export type Time = bigint;
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approvePartner' : ActorMethod<[Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllPartnerApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'getAllPartners' : ActorMethod<[], Array<PartnerProfile>>,
  'getAllPayoutRecords' : ActorMethod<
    [],
    Array<[Principal, Array<PayoutRecord>]>
  >,
  'getAllPerformanceData' : ActorMethod<
    [],
    Array<[Principal, PerformanceMetrics]>
  >,
  'getCallerApprovalStatus' : ActorMethod<[], ApprovalStatus>,
  'getCallerPayoutRecords' : ActorMethod<[], Array<PayoutRecord>>,
  'getCallerPerformanceMetrics' : ActorMethod<[], [] | [PerformanceMetrics]>,
  'getCallerProfile' : ActorMethod<[], [] | [PartnerProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPartnerApprovalStatus' : ActorMethod<[Principal], ApprovalStatus>,
  'getPartnerDashboard' : ActorMethod<
    [],
    {
      'metrics' : PerformanceMetrics,
      'approvalStatus' : ApprovalStatus,
      'payouts' : Array<PayoutRecord>,
      'profile' : PartnerProfile,
    }
  >,
  'getPartnerProfile' : ActorMethod<[Principal], PartnerProfile>,
  'getPayoutRecords' : ActorMethod<[Principal], Array<PayoutRecord>>,
  'getPerformanceMetrics' : ActorMethod<[Principal], PerformanceMetrics>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'recordClick' : ActorMethod<[Principal], undefined>,
  'recordConversion' : ActorMethod<[Principal, number], undefined>,
  'registerPartner' : ActorMethod<[PartnerProfile], undefined>,
  'rejectPartner' : ActorMethod<[Principal], undefined>,
  'requestApproval' : ActorMethod<[], undefined>,
  'requestPayout' : ActorMethod<[number], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'updatePayoutStatus' : ActorMethod<
    [
      Principal,
      bigint,
      { 'pending' : null } |
        { 'completed' : null } |
        { 'failed' : null },
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];