/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});
export const Time = IDL.Int;
export const PartnerProfile = IDL.Record({
  'contactName' : IDL.Text,
  'businessName' : IDL.Text,
  'email' : IDL.Text,
  'website' : IDL.Text,
  'applicationDate' : Time,
});
export const PayoutRecord = IDL.Record({
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'failed' : IDL.Null,
  }),
  'amount' : IDL.Float64,
  'payoutDate' : Time,
});
export const PerformanceMetrics = IDL.Record({
  'clicks' : IDL.Nat,
  'lastUpdated' : Time,
  'commissionEarned' : IDL.Float64,
  'conversions' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approvePartner' : IDL.Func([IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllPartnerApprovals' : IDL.Func(
      [],
      [IDL.Vec(UserApprovalInfo)],
      ['query'],
    ),
  'getAllPartners' : IDL.Func([], [IDL.Vec(PartnerProfile)], ['query']),
  'getAllPayoutRecords' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(PayoutRecord)))],
      ['query'],
    ),
  'getAllPerformanceData' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, PerformanceMetrics))],
      ['query'],
    ),
  'getCallerApprovalStatus' : IDL.Func([], [ApprovalStatus], ['query']),
  'getCallerPayoutRecords' : IDL.Func([], [IDL.Vec(PayoutRecord)], ['query']),
  'getCallerPerformanceMetrics' : IDL.Func(
      [],
      [IDL.Opt(PerformanceMetrics)],
      ['query'],
    ),
  'getCallerProfile' : IDL.Func([], [IDL.Opt(PartnerProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPartnerApprovalStatus' : IDL.Func(
      [IDL.Principal],
      [ApprovalStatus],
      ['query'],
    ),
  'getPartnerDashboard' : IDL.Func(
      [],
      [
        IDL.Record({
          'metrics' : PerformanceMetrics,
          'approvalStatus' : ApprovalStatus,
          'payouts' : IDL.Vec(PayoutRecord),
          'profile' : PartnerProfile,
        }),
      ],
      ['query'],
    ),
  'getPartnerProfile' : IDL.Func([IDL.Principal], [PartnerProfile], ['query']),
  'getPayoutRecords' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(PayoutRecord)],
      ['query'],
    ),
  'getPerformanceMetrics' : IDL.Func(
      [IDL.Principal],
      [PerformanceMetrics],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'recordClick' : IDL.Func([IDL.Principal], [], []),
  'recordConversion' : IDL.Func([IDL.Principal, IDL.Float64], [], []),
  'registerPartner' : IDL.Func([PartnerProfile], [], []),
  'rejectPartner' : IDL.Func([IDL.Principal], [], []),
  'requestApproval' : IDL.Func([], [], []),
  'requestPayout' : IDL.Func([IDL.Float64], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'updatePayoutStatus' : IDL.Func(
      [
        IDL.Principal,
        IDL.Nat,
        IDL.Variant({
          'pending' : IDL.Null,
          'completed' : IDL.Null,
          'failed' : IDL.Null,
        }),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  const Time = IDL.Int;
  const PartnerProfile = IDL.Record({
    'contactName' : IDL.Text,
    'businessName' : IDL.Text,
    'email' : IDL.Text,
    'website' : IDL.Text,
    'applicationDate' : Time,
  });
  const PayoutRecord = IDL.Record({
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'completed' : IDL.Null,
      'failed' : IDL.Null,
    }),
    'amount' : IDL.Float64,
    'payoutDate' : Time,
  });
  const PerformanceMetrics = IDL.Record({
    'clicks' : IDL.Nat,
    'lastUpdated' : Time,
    'commissionEarned' : IDL.Float64,
    'conversions' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approvePartner' : IDL.Func([IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllPartnerApprovals' : IDL.Func(
        [],
        [IDL.Vec(UserApprovalInfo)],
        ['query'],
      ),
    'getAllPartners' : IDL.Func([], [IDL.Vec(PartnerProfile)], ['query']),
    'getAllPayoutRecords' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(PayoutRecord)))],
        ['query'],
      ),
    'getAllPerformanceData' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, PerformanceMetrics))],
        ['query'],
      ),
    'getCallerApprovalStatus' : IDL.Func([], [ApprovalStatus], ['query']),
    'getCallerPayoutRecords' : IDL.Func([], [IDL.Vec(PayoutRecord)], ['query']),
    'getCallerPerformanceMetrics' : IDL.Func(
        [],
        [IDL.Opt(PerformanceMetrics)],
        ['query'],
      ),
    'getCallerProfile' : IDL.Func([], [IDL.Opt(PartnerProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPartnerApprovalStatus' : IDL.Func(
        [IDL.Principal],
        [ApprovalStatus],
        ['query'],
      ),
    'getPartnerDashboard' : IDL.Func(
        [],
        [
          IDL.Record({
            'metrics' : PerformanceMetrics,
            'approvalStatus' : ApprovalStatus,
            'payouts' : IDL.Vec(PayoutRecord),
            'profile' : PartnerProfile,
          }),
        ],
        ['query'],
      ),
    'getPartnerProfile' : IDL.Func(
        [IDL.Principal],
        [PartnerProfile],
        ['query'],
      ),
    'getPayoutRecords' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(PayoutRecord)],
        ['query'],
      ),
    'getPerformanceMetrics' : IDL.Func(
        [IDL.Principal],
        [PerformanceMetrics],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'recordClick' : IDL.Func([IDL.Principal], [], []),
    'recordConversion' : IDL.Func([IDL.Principal, IDL.Float64], [], []),
    'registerPartner' : IDL.Func([PartnerProfile], [], []),
    'rejectPartner' : IDL.Func([IDL.Principal], [], []),
    'requestApproval' : IDL.Func([], [], []),
    'requestPayout' : IDL.Func([IDL.Float64], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'updatePayoutStatus' : IDL.Func(
        [
          IDL.Principal,
          IDL.Nat,
          IDL.Variant({
            'pending' : IDL.Null,
            'completed' : IDL.Null,
            'failed' : IDL.Null,
          }),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };